const AppAssets = {
    background_card: "/assets/background_card.png",
    star: "/assets/star.png",
    logo: "/assets/dope-logo.jpg",
    crown: "/assets/crown.png",
    ia: "/assets/microchip.png",
    less: "/assets/less-sign.png",
    artificial_intelligence: "/assets/artificial-intelligence.png",
    trophy: "/assets/trophy.png",
    background_image: "/assets/hero_home_02.jpg",
    hit: "/assets/hit.png",
    ball_grafic: "/assets/ball_grafic.png",
    brand: "/assets/brand.png",
    background_session_1: "/assets/background_session_1.jpeg",
    background_session_2: "/assets/background_session_2.jpeg",
    background_session_3: "/assets/background_session_3.jpeg",
    background_session_4: "/assets/background_session_4.jpeg",
    background_session_5: "/assets/background_session_5.jpeg",
    background_session_6: "/assets/background_session_6.jpg",
    bottom_cover_white: "/assets/bottom_cover_white.png",
    background_03_home_02: "/assets/background_03_home_02.jpg",
    background_04_home_01: "/assets/background_04_home_01.png",
    background_04_home_02: "/assets/background_04_home_02.png",
    logo_icon: "/assets/logo_icon.png",
    signature: "/assets/signature.png",
    logo_black: "/assets/logo_black.png",
    card_img_1: "/assets/card_img_1.png",
    card_img_2: "/assets/card_img_2.png",
    card_img_3: "/assets/card_img_3.png",
    card_img_4: "/assets/card_img_4.png",
    card_img_5: "/assets/card_img_5.png",
    logo_red: "/assets/logo_red.png"
}

export default AppAssets;